/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.user;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Oncologist.Oncologist;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OncologistAppointment;
import Business.WorkQueue.OncologistAppointmentDirectory;
import Business.WorkQueue.appointmentCheck;
import Business.user.User;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajay09
 */
public class oncologistAppointmentInterface extends javax.swing.JPanel {
    private final JPanel container;
    private final EcoSystem ecosystem;
    private final UserAccount userAccount;
    /**
     * Creates new form oncologistAppointmentInterface
     */
    public oncologistAppointmentInterface(JPanel container,EcoSystem ecosystem,UserAccount userAccount) {
        initComponents();
        this.container=container;
        this.ecosystem=ecosystem;
        this.userAccount=userAccount;
        combobox();
    }
    
     public void combobox()
    {
        ArrayList<Oncologist> onc=ecosystem.getOncologistsDirectory().getOncDir();
        int s= onc.size();
        ArrayList<String> spe =new ArrayList<String>();
        for(int i=0;i<s;i++)
        {
            Oncologist onc1=onc.get(i);
            if(!spe.contains(onc1.getSpealization()))
                    {
                        spe.add(onc1.getSpealization());
                    }
            
        }
        for(int i=0;i<spe.size();i++)
        {
            ddSpecialization.addItem(spe.get(i));
        }
        
    }
     
     
     public void table()
    {
        String spe=ddSpecialization.getSelectedItem().toString();
        ArrayList<Oncologist> onc= ecosystem.getOncologistsDirectory().getOncDir();
        int s=onc.size();
        ArrayList<String> spe1 =new ArrayList<String>();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Name","Hospital","Spealization","Phone Number"}));
        for(int i=0;i<s;i++)
        {
            Oncologist onc1=onc.get(i);
            if(onc1.getSpealization().matches(spe))
            {
                DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();    
                String s1[]={onc1.getFirstname(),onc1.getLastname(),onc1.getSpealization(),onc1.getPhoneNumber()};
                t2.addRow(s1);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblTime = new javax.swing.JLabel();
        boxTime = new javax.swing.JComboBox<>();
        btnBookApp = new javax.swing.JButton();
        btnAppStatus = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        ddSpecialization = new javax.swing.JComboBox<>();
        tblAppointment = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lblDate.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 204, 204));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setText("Date :");
        lblDate.setPreferredSize(new java.awt.Dimension(70, 30));

        jDateChooser1.setMaxSelectableDate(new java.util.Date(1641016905000L));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(140, 30));

        lblTime.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(204, 204, 204));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("Time :");

        boxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00", "17:00-18:00" }));

        btnBookApp.setBackground(new java.awt.Color(195, 233, 245));
        btnBookApp.setText("Book Appointment");

        btnAppStatus.setBackground(new java.awt.Color(195, 233, 245));
        btnAppStatus.setText("View Appointment Status");

        lblTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Doctor's Appointment");

        lblSpecialization.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblSpecialization.setForeground(new java.awt.Color(204, 204, 204));
        lblSpecialization.setText("Specialization :");

        ddSpecialization.setPreferredSize(new java.awt.Dimension(140, 30));
        ddSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSpecializationActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Hospital", "Specialization", "Phone Number"
            }
        ));
        tblAppointment.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(lblTitle))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSpecialization)
                            .addGap(143, 143, 143)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBookApp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAppStatus)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(165, 165, 165))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tblAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitle)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialization)
                    .addComponent(ddSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(tblAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppStatus)
                    .addComponent(btnBookApp))
                .addGap(231, 231, 231))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ddSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSpecializationActionPerformed
        // TODO add your handling code here:
        table();
    }//GEN-LAST:event_ddSpecializationActionPerformed
    
    public boolean check(String s,String d1,String date)
    {
        boolean b=false;
        appointmentCheck check= ecosystem.getAppcheck();
        Map<String,List<String>> a=check.getPeopleByFirstName();
        for (Map.Entry mapElement : a.entrySet()) {
            if(mapElement.getKey().toString().matches(s))
            {
                List<String>a1=(List)mapElement.getValue();
                String s1=a1.get(0);
                String s2=a1.get(1);
                if(s1.matches(d1))
                {
                    if(s2.matches(date))
                    {
                        b=true;
                        break;
                    }
                }
            } 
           
        }
        return b;
    }
    
    public void oncologistAppointmentUI()
    {
        appointmentStatus as=new appointmentStatus(container,ecosystem,userAccount);
        jPanel1.add(as);
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTime;
    private javax.swing.JButton btnAppStatus;
    private javax.swing.JButton btnBookApp;
    private javax.swing.JComboBox<String> ddSpecialization;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane tblAppointment;
    // End of variables declaration//GEN-END:variables
}
