/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.user;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Oncologist.Oncologist;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OncologistAppointment;
import Business.WorkQueue.OncologistAppointmentDirectory;
import Business.WorkQueue.appointmentCheck;
import Business.user.User;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajay09
 */
public class oncologistAppointmentUI extends javax.swing.JPanel {
    private final JPanel container;
    private final EcoSystem ecosystem;
    private final UserAccount userAccount;

    /**
     * Creates new form oncologistAppointment
     */
    public oncologistAppointmentUI(JPanel container,EcoSystem ecosystem,UserAccount userAccount) {
        initComponents();
        this.container=container;
        this.ecosystem=ecosystem;
        this.userAccount=userAccount;
        combobox();
    }
    
    public void combobox()
    {
        ArrayList<Oncologist> onc=ecosystem.getOncologistsDirectory().getOncDir();
        int s= onc.size();
        ArrayList<String> spe =new ArrayList<String>();
        for(int i=0;i<s;i++)
        {
            Oncologist onc1=onc.get(i);
            if(!spe.contains(onc1.getSpealization()))
                    {
                        spe.add(onc1.getSpealization());
                    }
            
        }
        for(int i=0;i<spe.size();i++)
        {
            ddSpecialization.addItem(spe.get(i));
        }
        
    }
    
    public void table()
    {
        String spe=ddSpecialization.getSelectedItem().toString();
        ArrayList<Oncologist> onc= ecosystem.getOncologistsDirectory().getOncDir();
        int s=onc.size();
        ArrayList<String> spe1 =new ArrayList<String>();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Name","Hospital","Spealization","Phone Number"}));
        for(int i=0;i<s;i++)
        {
            Oncologist onc1=onc.get(i);
            if(onc1.getSpealization().matches(spe))
            {
                DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();    
                String s1[]={onc1.getFirstname(),onc1.getLastname(),onc1.getSpealization(),onc1.getPhoneNumber()};
                t2.addRow(s1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        ddSpecialization = new javax.swing.JComboBox<>();
        tblAppointment = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblTime = new javax.swing.JLabel();
        boxTime = new javax.swing.JComboBox<>();
        btnBookApp = new javax.swing.JButton();
        btnAppStatus = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Doctor's Appointment");

        lblSpecialization.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblSpecialization.setForeground(new java.awt.Color(204, 204, 204));
        lblSpecialization.setText("Specialization :");

        ddSpecialization.setPreferredSize(new java.awt.Dimension(140, 30));
        ddSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSpecializationActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Hospital", "Specialization", "Phone Number"
            }
        ));
        tblAppointment.setViewportView(jTable1);

        lblDate.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 204, 204));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setText("Date :");
        lblDate.setPreferredSize(new java.awt.Dimension(70, 30));

        jDateChooser1.setMaxSelectableDate(new java.util.Date(1641016905000L));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(140, 30));
        lblTime.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(204, 204, 204));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("Time :");

        boxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00", "17:00-18:00" }));
        boxTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTimeActionPerformed(evt);
            }
        });

        btnBookApp.setBackground(new java.awt.Color(195, 233, 245));
        btnBookApp.setText("Book Appointment");
        btnBookApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppActionPerformed(evt);
            }
        });

        btnAppStatus.setBackground(new java.awt.Color(195, 233, 245));
        btnAppStatus.setText("View Appointment Status");
        btnAppStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSpecialization)
                        .addGap(56, 56, 56)
                        .addComponent(ddSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(tblAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)

                        .addGap(116, 116, 116)
                        .addComponent(ddSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBookApp)
                        .addGap(58, 58, 58)
                        .addComponent(btnAppStatus)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tblAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addGap(39, 39, 39)
                        .addComponent(boxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTitle)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization))
                .addGap(42, 42, 42)
                .addComponent(tblAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppStatus)
                    .addComponent(btnBookApp))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ddSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSpecializationActionPerformed
        // TODO add your handling code here:
        table();
    }//GEN-LAST:event_ddSpecializationActionPerformed

    private void btnBookAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
        int t1=jTable1.getSelectedRow();
        if(t1>=0)
        {
            if(jDateChooser1.getDate()!=null)
            {
                int x = 1 + (int) (Math.random() * 100);
                boolean b=false;
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String d1 = sdf.format(jDateChooser1.getDate());
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDateTime d2 = LocalDateTime.now();
                String s=(t.getValueAt(t1, 0).toString());
                String date=boxTime.getSelectedItem().toString();
                if(d1.compareTo(d2.toString()) >= 0) {
                    b=check(s,d1,date);
                    if(b==false)
                    {
                        OncologistAppointment OA=new OncologistAppointment();
                        OA.setOncologistID(x);
                        OA.setOncologistName(s);
                        String s1=(t.getValueAt(t1, 1).toString());
                        OA.setLastName(s1);
                        OA.setDate(d1);
                        OA.setStatus("Appointment Booked");
                        OA.setTime(date);
                        User u=(User)(userAccount);
                        OA.setUserID(u.getUserID());
                        OA.setUserName(u.getOncologistName());
                        OncologistAppointmentDirectory OAD=ecosystem.getOncologistAppointmentDirectory();
                        OAD.addRequest(OA);
                        appointmentCheck check= ecosystem.getAppcheck();
                        Map<String,List<String>> a=check.getPeopleByFirstName();
                        List<String> list = new ArrayList<String>();
                        list.add(d1);
                        list.add(boxTime.getSelectedItem().toString());
                        a.put(s, list);
                        DB4OUtil.dB4OUtil.storeSystem(ecosystem);

                        //code to send email
                        {
                            String ToEmail = u.getEmailID();
                            String myAccountEmail = "test123";
                            String password = "test123";

                            Properties properties = new Properties();
                            properties.put("mail.smtp.auth","true");
                            properties.put("mail.smtp.starttls.enable","true");
                            properties.put("mail.smtp.host","smtp.gmail.com");
                            properties.put("mail.smtp.port","587");

                            Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
                                protected PasswordAuthentication getPasswordAuthentication(){
                                    return new PasswordAuthentication(myAccountEmail, password);
                                }

                            });
                            try{
                                MimeMessage message = new MimeMessage(session);
                                message.setFrom(new InternetAddress(myAccountEmail));
                                message.addRecipient(javax.mail.Message.RecipientType.TO, new InternetAddress(ToEmail));
                                message.setSubject("Appointment Booked!!");
                                message.setText("Doctor : "+s+"\n"+"Hospital : "+s1+"\n"+"Date : "+d1+"\n"+"Time : "+boxTime.getSelectedItem().toString());
                                javax.mail.Transport.send(message);
                            }catch(Exception ex){
                                System.out.println(""+ex);
                            }

                        }
                        //end of code
                        JOptionPane.showMessageDialog(null,"Appointment booked!!");

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Appointment slot not available!!");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Appointment Available from Tomorrow");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Pick A Date!!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Select a Doctor!!");
        }
    }//GEN-LAST:event_btnBookAppActionPerformed

    private void btnAppStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppStatusActionPerformed
        // TODO add your handling code here:
        oncologistAppointmentUI();
    }//GEN-LAST:event_btnAppStatusActionPerformed

    private void boxTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTimeActionPerformed
    
    public boolean check(String s,String d1,String date)
    {
        boolean b=false;
        appointmentCheck check= ecosystem.getAppcheck();
        Map<String,List<String>> a=check.getPeopleByFirstName();
        for (Map.Entry mapElement : a.entrySet()) {
            if(mapElement.getKey().toString().matches(s))
            {
                List<String>a1=(List)mapElement.getValue();
                String s1=a1.get(0);
                String s2=a1.get(1);
                if(s1.matches(d1))
                {
                    if(s2.matches(date))
                    {
                        b=true;
                        break;
                    }
                }
            } 
           
        }
        return b;
    }
    public void oncologistAppointmentUI()
    {
        appointmentStatus as=new appointmentStatus(container,ecosystem,userAccount);
        jPanel1.add(as);
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.next(jPanel1); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTime;
    private javax.swing.JButton btnAppStatus;
    private javax.swing.JButton btnBookApp;
    private javax.swing.JComboBox<String> ddSpecialization;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane tblAppointment;
    // End of variables declaration//GEN-END:variables
}
