/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Ambulance;

import Business.Ambulance.Ambulance;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyReport;
import Business.WorkQueue.EmergencyReportDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chand
 */
public class AmbulanceUI extends javax.swing.JPanel {
     private final JPanel container;
    private final EcoSystem ecoSystem;
    private final UserAccount ua;
    /**
     * Creates new form AmbulanceUI
     */
    public AmbulanceUI(JPanel container,EcoSystem ecoSystem,UserAccount ua) {
        initComponents();
        this.container=container;
        this.ecoSystem=ecoSystem;
        this.ua=ua;
        populate_table();
    }
    
    public void populate_table()
    {
        EmergencyReportDirectory red=ecoSystem.getEmergencyReportDirectory();
        ArrayList<EmergencyReport> ol=red.getUser();
        int u=ol.size();
        System.out.println(u);
        for(int i=0;i<u;i++)
        {
            EmergencyReport o=ol.get(i);
            if(o.getEmergency().matches("Medical"))
            {
                DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
                String s1=String.valueOf(o.getId());
                
                
                String s[]={s1,o.getName(),o.getEmergency(),o.getLocation(),o.getStatus(),o.getResponse()};
                t2.addRow(s);
            
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAmbulanceRespond = new javax.swing.JButton();
        btnAmbulanceFalseAlarm = new javax.swing.JButton();
        btnCloseAmbulance = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Emergency", "Location", "Status", "Response"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAmbulanceRespond.setBackground(new java.awt.Color(189, 195, 199));
        btnAmbulanceRespond.setText("Respond");
        btnAmbulanceRespond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbulanceRespondActionPerformed(evt);
            }
        });

        btnAmbulanceFalseAlarm.setBackground(new java.awt.Color(189, 195, 199));
        btnAmbulanceFalseAlarm.setText("False Alaram");
        btnAmbulanceFalseAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbulanceFalseAlarmActionPerformed(evt);
            }
        });

        btnCloseAmbulance.setBackground(new java.awt.Color(189, 195, 199));
        btnCloseAmbulance.setText("Close Case");
        btnCloseAmbulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAmbulanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnAmbulanceRespond)
                        .addGap(167, 167, 167)
                        .addComponent(btnAmbulanceFalseAlarm)
                        .addGap(137, 137, 137)
                        .addComponent(btnCloseAmbulance)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAmbulanceRespond)
                    .addComponent(btnAmbulanceFalseAlarm)
                    .addComponent(btnCloseAmbulance))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbulanceRespondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbulanceRespondActionPerformed
        // TODO add your handling code here:
        DefaultTableModel  t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
            int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
            System.out.println("id"+s);
            EmergencyReportDirectory red=ecoSystem.getEmergencyReportDirectory();
            ArrayList<EmergencyReport> ol=red.getUser();
            int u=ol.size();
            Ambulance a=(Ambulance)ua;
            for(int i=0;i<u;i++)
            {
                EmergencyReport o=ol.get(i);
                if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
                {
                    if(o.getStatus().matches("Closed"))
                    {
                        JOptionPane.showMessageDialog(null, "Emergency Closed");
                    }
                    else if(o.getStatus().matches("False Alaram"))
                    {
                        JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                    }
                    else if(o.getResponse().matches("No Response"))
                    {
                        o.setResponse(a.getAmbulanceName()+" "+"Responded");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Already Responded!!");
                    }
                }

            }
            jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Emergency","Location","Status","Response"}));
            populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }
    }//GEN-LAST:event_btnAmbulanceRespondActionPerformed

    private void btnAmbulanceFalseAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbulanceFalseAlarmActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
            int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
            System.out.println("id"+s);
            EmergencyReportDirectory red=ecoSystem.getEmergencyReportDirectory();
            ArrayList<EmergencyReport> ol=red.getUser();
            int u=ol.size();
            for(int i=0;i<u;i++)
            {
                EmergencyReport o=ol.get(i);
                if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
                {
                    if(o.getStatus().matches("Closed"))
                    {
                        JOptionPane.showMessageDialog(null, "Emergency Closed");
                    }
                    else if(o.getStatus().matches("False Alaram"))
                    {
                        JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                    }
                    else if(o.getResponse().matches("No Response"))
                    {
                        JOptionPane.showMessageDialog(null, "respond to emergency");
                    }
                    else
                    {
                        o.setStatus("False Alaram");
                    }
                    /*if(o.getStatus().matches("Closed"))
                    {
                        if(o.getStatus().matches("False Alaram"))
                        {
                            if(o.getAmbulance().matches("No Response"))
                            {
                                JOptionPane.showMessageDialog(null, "Respond to the emergency");
                                break;
                            }
                            else
                            {
                                o.setStatus("False Alaram");

                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                            break;
                        }

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Emergency Closed");
                        break;
                    }*/

                }

            }
            jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Emergency","Location","Status","Response"}));
            populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }
    }//GEN-LAST:event_btnAmbulanceFalseAlarmActionPerformed

    private void btnCloseAmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAmbulanceActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
            int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
            System.out.println("id"+s);
            EmergencyReportDirectory red=ecoSystem.getEmergencyReportDirectory();
            ArrayList<EmergencyReport> ol=red.getUser();
            int u=ol.size();
            for(int i=0;i<u;i++)
            {
                EmergencyReport o=ol.get(i);
                if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
                {
                    if(o.getStatus().matches("Closed"))
                    {
                        JOptionPane.showMessageDialog(null, "Emergency Closed");
                    }
                    else if(o.getStatus().matches("False Alaram"))
                    {
                        JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                    }
                    else if(o.getResponse().matches("No Response"))
                    {
                        JOptionPane.showMessageDialog(null, "respond to emergency");
                    }
                    else
                    {
                        o.setStatus("Closed");
                    }

                }

            }
            jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Emergency","Location","Status","Response"}));
            populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }

    }//GEN-LAST:event_btnCloseAmbulanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbulanceFalseAlarm;
    private javax.swing.JButton btnAmbulanceRespond;
    private javax.swing.JButton btnCloseAmbulance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
